---
name: build-and-push

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

env:
  REGISTRY: ${{ vars.REGISTRY }}
  # TRURALY_GITEA_SSH: ${{ secrets.TRURALY_GITEA_SSH }}

jobs:
  release-image:
    runs-on: [deploy, uopve]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build and push
        run: |
          docker build \
            -t $REGISTRY/kilocli-server:latest \
            -f ./Dockerfile . 
          docker push $REGISTRY/kilocli-server:latest
